name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install CUnit
        run: sudo apt-get update && sudo apt-get install -y libcunit1-dev

      - name: Run tests
        run: make test CUNIT_DIR=/usr

  build:
    name: Build and Upload Executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install CUnit
        run: sudo apt-get update && sudo apt-get install -y libcunit1-dev

      - name: Build executable
        run: make all CUNIT_DIR=/usr

      - name: Upload `out/` folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-output
          path: out/
